name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon

      - name: Rename jar file
        run: |
          cd build/libs
          for f in *-build.jar; do
            mv "$f" "${f/-build/}.jar"
          done

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Release"
          tag_name: ${{ github.ref_name }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
