name: Build and Release

on:
  push:
    branches: [ "main" ]

concurrency:
  group: "latest"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to create/update releases

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle (ShadowJar)
        run: ./gradlew shadowJar --no-daemon

      - name: Rename jar file
        run: |
          cd build/libs
          for f in *-all.jar; do
            newname="${f/-all/}"     # strip '-all'
            mv "$f" "$newname"
          done
          ls -lh

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Release"
          tag_name: "latest"
          files: build/libs/*.jar
          overwrite: true            # overwrite existing asset with same name
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
